title: TeXnical Details
email: code@seanallred.com
description: >
  A personal and development blog.  Topics range from TeX and Emacs
  to social politics to philosophical questions and matters of faith.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.seanallred.com"
twitter_username: vermiculus
github_username:  vermiculus

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

redcarpet:
#  extensions: ["fenced_code_blocks", "footnotes"]
  extensions: ["footnotes"]

#  LocalWords:  github username vermiculus LocalWords baseurl blog
